import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState,useEffect} from 'react'
import axios from 'axios'
export default function Home() {
  const  postdata=async(e)=>{
    try{
    e.preventDefault();
    const selected=e.target.files[0];
    console.log(e.target.files[0])
    const formData=new FormData();
    formData.append("csv_file",e.target.files[0])
    const res= await axios.post('http://127.0.0.1:8000/uploadfile',formData,{
      headers:{
        'accept': 'application/json',
        'enctype':'multipart/form-data'
      }
    })
    console.log(res.data);
    }
    catch(err){
      console.log(err)
    }
   }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form>
     <h1>Upload the CSV file to the database</h1>
     <input type="file" onChange={postdata} />
     {/*file && <div>{file.name}</div>*/}

     </form>    
    </div>
  )
}
