import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState,useEffect} from 'react'
import axios from 'axios'

export default function Home() {
  const [datafa, setDatafa] = useState(null);

  const message =async (e) => {
    let selected=e.target.files[0];
    console.log(selected);
    let data=new FormData();
    data.append('file',selected)
    console.log(data);
    try {

      
      let res=await axios.post('http://127.0.0.1:8000/uploadfile/',selected,{
        headers: {
          'enctype': 'multipart/form-data'
        }
      });
      let result=res.data;
      setDatafa(result);
      console.log(res.data);
    }
    catch(err) {
      console.error(err);
    }
  };
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form>
      <input type="file" onChange={message} />
        <input type="submit" />
      </form>
     
     {!datafa ?
     <h1>loading...</h1>
     :
<h1>{datafa}</h1>
     }

     <h1>hello</h1>
    </div>
  )
}
