import Head from "next/head";
import { useState } from "react";
import Header from '../components/Header';
import axios from "axios";
export default function Home() {
  const [file, setFile] = useState(null);
  const [data, setData] = useState(null);
  const postdata = async (e) => {
    try {
      e.preventDefault();
      const selected = e.target.files[0];
      setFile(selected);
      const formData = new FormData();
      formData.append("csv_file", e.target.files[0]);
      const res = await axios.post(
        "http://127.0.0.1:8000/uploadfile",
        formData,
        {
          headers: {
            accept: "application/json",
            enctype: "multipart/form-data",
          },
        }
      );
      const vr = JSON.parse(res.data.csvdata);
      // debugger;
      console.log(res);
      setData(vr);

      // console.log(data)
    } catch (err) {
      console.log(err);
    }
  };

  const renderHeader = (data1, index) => {
    let headerJSX = [];
    let kl = 0;
    Object.entries(data1).map((value, i) => {
      if (index === 0) {
        headerJSX.push(
          <div key={(kl += 1)} className="header-value p-2 ">
            {value[0]}
          </div>
        );
      }
    });
    return headerJSX;
  };
  const renderdata = (data1, index) => {
    let k = 0;
    let JSX = [];
    Object.entries(data1).map((value, i) => {
      JSX.push(
        <>
          <div key={(k += 1)} className="actual-value p-2 max-w-[200px] ">
            <div>{value[1]}</div>
          </div>
        </>
      );
    });
    JSX.push(<br />);
    //debugger
    return <div className="flex">{JSX}</div>;
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <form>

        <div className="mb-12 ml-auto border text-center h-[200px] mt-[150px] items-center">
        <h1 className="item-center m-5">Upload the CSV file to the database</h1>
        <input type="file" className="m-5 placeholder-shown:m-1.5" placeholder="PLease select  the CSV file " onChange={postdata} />
        </div>
        
        <div className="w-9/12 h-screen m-auto items-center text-center overflow-x-auto overflow-y-auto">
          <div className="flex ">
            {file !== null &&
              data !== null &&
              data.map((data1, index) => {
                return renderHeader(data1, index);
              })}
          </div>
          <div className="w-full overflow-hidden">
            {file !== null && data == null && (
              <div>
                <div className="border border-blue-300 shadow rounded-md p-4 max-w-sm w-full mx-auto">
                  <div  className="animate-pulse flex space-x-4">
                    <div  className="rounded-sm bg-blue-400 h-12 w-12"></div>
                    <div  className="flex-1 space-y-4 py-1">
                      <div  className="h-4 bg-blue-400 rounded w-3/4"></div>
                      <div  className="space-y-2">
                        <div  className="h-4 bg-blue-400 rounded"></div>
                        <div  className="h-4 bg-blue-400 rounded w-5/6"></div>
                      </div>
                    </div>
                  </div>
                </div>
                <svg class="animate-bounce w-6 h-6 ...">
  
                  </svg>
              </div>
            )}
            {file !== null &&
              data !== null &&
              data.map((data1, index) => {
               
                return renderdata(data1, index);
              })}
          </div>
          {/*file && <div>{file.name}</div>*/}
        </div>
      </form>
     
    </div>
  );
}
